In [28]:
import time
import torch
import numpy as np

In [10]:
scalar = torch.tensor(1)
print(scalar)

tensor(1)


In [14]:
vector = torch.tensor([1, 2, 3])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector.dtype)

tensor([1, 2, 3])
1
torch.Size([3])
torch.int64


In [13]:
matrix = torch.tensor([[10.0, 20.0], 
                       [30.0, 40.0]])
print(matrix.ndim)
print(matrix.shape)
print(matrix.dtype)

2
torch.Size([2, 2])
torch.float32


In [16]:
rand_matrix = torch.rand(size=(5, 5))
print(rand_matrix)

tensor([[0.7939, 0.2418, 0.5322, 0.5181, 0.1969],
        [0.4158, 0.5752, 0.1911, 0.5497, 0.1675],
        [0.6240, 0.2548, 0.2888, 0.9078, 0.9913],
        [0.1139, 0.5484, 0.5020, 0.2506, 0.2165],
        [0.0744, 0.2180, 0.1227, 0.3530, 0.3564]])


In [18]:
tensor = torch.multiply(vector, 10)
print(tensor)

tensor([10, 20, 30])


In [19]:
# Hadamard product
print(matrix * matrix)

tensor([[ 100.,  400.],
        [ 900., 1600.]])


In [21]:
tensor_1 = torch.rand((2,3))
tensor_2 = torch.rand((3,2))
print(torch.matmul(tensor_1, tensor_2))
print(tensor_1 @ tensor_2)


tensor([[0.5037, 0.7007],
        [0.7628, 1.4555]])
tensor([[0.5037, 0.7007],
        [0.7628, 1.4555]])


In [23]:
tensor_3d = torch.tensor([[[10,20,30],
                           [40,50,60],
                           [70,80,90]], 
                           [[100,200,300],
                            [400,500,600],
                            [700,800,900]]])
print(tensor_3d[1, 0, 0])

tensor(100)


In [30]:
array = np.arange(1.0, 10.0)
tensor_3 = torch.from_numpy(array)
print(array)
print(tensor_3)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [32]:
tensor_4 = torch.ones(10) 
numpy_tensor = tensor_4.numpy()
print(tensor_4)
print(numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# tensor_on_gpu = tensor.to(device)

cpu


In [27]:
# check for gpu
if torch.backends.mps.is_available():
   mps_device = torch.device("mps")
   x = torch.ones(1, device=mps_device)
   print(x)
else:
   print("MPS device not found.")

tensor([1.], device='mps:0')


In [29]:
start_time = time.time()

# syncrocnize time with cpu, otherwise only time for oflaoding data to gpu would be measured
torch.mps.synchronize()

x = torch.ones(4000,4000, device="mps")
for _ in range(200):
   x += x

elapsed_time = time.time() - start_time
print( "GPU Time: ", elapsed_time)

GPU Time:  0.403883695602417
